### ISSUE TITLE
Global mediaType ignored in parsing of body

### ISSUE THREAD

**Issue by blindscreen** [an2deg/pyraml-parser#10]
To see this happen run the parser with the github api: http://api-portal.anypoint.mulesoft.com/github/api/github-api-v3/github-api-v3.raml

This has a global mediaType defined as application/json, so it is not explicitly defined in each body...

```
 /members:
    type: collection
    get:
      description: |
        List team members.
        In order to list members in a team, the authenticated user must be a member
        of the team.
      responses:
        200:
          body:
            schema: |
              {
                  "$schema": "http://json-schema.org/draft-03/schema",
                  "type": "array",
                  "list": [
                  	{
                  		"properties": {
                  			"login": {
                  				"type": "string"
                  			},
              			    "id": {
              			    	"type": "integer"
              			    },
              			    "avatar_url": {
              			    	"type": "string"
              			    },
              			    "gravatar_id": {
              			    	"type": "string"
              			    },
              			    "url": {
              			    	"type": "string"
              			    }
                  		},
                  		"type": "object"
                  	}
                  ]
              }
            example: |
              [
                {
                  "login": "octocat",
                  "id": 1,
                  "avatar_url": "https://github.com/images/error/octocat_happy.gif",
                  "gravatar_id": "somehexcode",
                  "url": "https://api.github.com/users/octocat"
                }
              ]
```

This currently yields the error:
```
Traceback (most recent call last):
  File "parser.py", line 10, in <module>
    p = pyraml.parser.load('github.raml')
  File "/Users/tsmith5/dev/pyraml-parser/pyraml/parser.py", line 107, in load
    return parse(c, relative_path)
  File "/Users/tsmith5/dev/pyraml-parser/pyraml/parser.py", line 139, in parse
    resources[property_name] = parse_resource(context, property_name, root)
  File "/Users/tsmith5/dev/pyraml-parser/pyraml/parser.py", line 194, in parse_resource
    resources[property_name] = parse_resource(new_context, property_name, resource)
  File "/Users/tsmith5/dev/pyraml-parser/pyraml/parser.py", line 179, in parse_resource
    _method = parse_method(ParseContext(_method, c.relative_path), resource)
  File "/Users/tsmith5/dev/pyraml-parser/pyraml/parser.py", line 263, in parse_method
    method.responses = c.get_property_with_schema("responses", RamlMethod.responses)
  File "/Users/tsmith5/dev/pyraml-parser/pyraml/parser.py", line 70, in get_property_with_schema
    return property_schema.to_python(property_value)
  File "/Users/tsmith5/dev/pyraml-parser/pyraml/fields.py", line 379, in to_python
    for key, val in value.items()])
  File "/Users/tsmith5/dev/pyraml-parser/pyraml/fields.py", line 462, in to_python
    value = self.ref_class.from_json(value)
  File "/Users/tsmith5/dev/pyraml-parser/pyraml/model.py", line 122, in from_json
    raise ValidationError(errors)
pyraml.model.ValidationError
```

This can be fixed by specifying appplication/json in each body section, but ideally the parser should know that a global media type was specified

**Comment by an2deg** [comment]
I've added this situation to tests and fixed it. Please try code from latest master
