### ISSUE TITLE
RAML parser failed with attribute error

### ISSUE THREAD

**Issue by shari20** [an2deg/pyraml-parser#19]
>>> p=pyraml.parser.load("C:\Python27\test.raml")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python27\lib\site-packages\pyraml\parser.py", line 136, in load
    c, _ = _load_network_resource(uri)
  File "C:\Python27\lib\site-packages\pyraml\parser.py", line 451, in _load_netw
ork_resource
    with contextlib.closing(urllib2.urlopen(url, timeout=60.0)) as f:
AttributeError: 'Module_six_moves_urllib' object has no attribute 'urlopen'

**Comment by an2deg** [comment]
Hi Shari!

I've fixed the issue. Please try pyraml-parser version 0.1.5 from PyPi
Thank you!
